-- Financial Services CMS schema for Supabase
-- This model keeps layout/components in React and stores editable content in tables.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  site_name text not null,
  logo_url text default '',
  footer_cta_title text default '',
  footer_cta_body text default '',
  footer_cta_button_label text default '',
  footer_cta_button_url text default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint site_settings_single_row check (id = 1)
);

insert into public.site_settings (
  id,
  site_name,
  logo_url,
  footer_cta_title,
  footer_cta_body,
  footer_cta_button_label,
  footer_cta_button_url
)
values (
  1,
  'Content Management System',
  '',
  'Ready to take the next step?',
  'Book a free consultation today and let our team help you create a financial protection plan.',
  'Book a Free Consultation',
  '/contact'
)
on conflict (id) do nothing;

create table if not exists public.cms_pages (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  nav_label text not null,
  page_title text not null,
  page_description text default '',
  seo_title text default '',
  seo_description text default '',
  hero_title text default '',
  hero_body text default '',
  hero_primary_button_label text default '',
  hero_primary_button_url text default '',
  hero_secondary_button_label text default '',
  hero_secondary_button_url text default '',
  hero_image_url text default '',
  is_published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.cms_sections (
  id uuid primary key default gen_random_uuid(),
  page_id uuid not null references public.cms_pages(id) on delete cascade,
  section_key text not null,
  section_label text not null,
  section_type text not null check (
    section_type in (
      'hero',
      'content',
      'cards',
      'cta',
      'faq',
      'list'
    )
  ),
  title text default '',
  subtitle text default '',
  body text default '',
  image_url text default '',
  primary_button_label text default '',
  primary_button_url text default '',
  secondary_button_label text default '',
  secondary_button_url text default '',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint cms_sections_page_key_unique unique (page_id, section_key)
);

create table if not exists public.cms_section_items (
  id uuid primary key default gen_random_uuid(),
  section_id uuid not null references public.cms_sections(id) on delete cascade,
  title text not null,
  subtitle text default '',
  body text default '',
  image_url text default '',
  link_label text default '',
  link_url text default '',
  metadata jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  email text not null unique,
  role text not null default 'editor' check (role in ('admin', 'editor')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.is_cms_editor()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.users u
    where u.id = auth.uid()
      and u.role in ('admin', 'editor')
  );
$$;

drop trigger if exists trg_site_settings_updated_at on public.site_settings;
create trigger trg_site_settings_updated_at
before update on public.site_settings
for each row
execute function public.set_updated_at();

drop trigger if exists trg_cms_pages_updated_at on public.cms_pages;
create trigger trg_cms_pages_updated_at
before update on public.cms_pages
for each row
execute function public.set_updated_at();

drop trigger if exists trg_cms_sections_updated_at on public.cms_sections;
create trigger trg_cms_sections_updated_at
before update on public.cms_sections
for each row
execute function public.set_updated_at();

drop trigger if exists trg_cms_section_items_updated_at on public.cms_section_items;
create trigger trg_cms_section_items_updated_at
before update on public.cms_section_items
for each row
execute function public.set_updated_at();

drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
before update on public.users
for each row
execute function public.set_updated_at();

alter table public.site_settings enable row level security;
alter table public.cms_pages enable row level security;
alter table public.cms_sections enable row level security;
alter table public.cms_section_items enable row level security;
alter table public.users enable row level security;

drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings"
on public.site_settings
for select
using (true);

drop policy if exists "Editors can manage site settings" on public.site_settings;
create policy "Editors can manage site settings"
on public.site_settings
for all
using (public.is_cms_editor())
with check (public.is_cms_editor());

drop policy if exists "Public can read published pages" on public.cms_pages;
create policy "Public can read published pages"
on public.cms_pages
for select
using (is_published = true or public.is_cms_editor());

drop policy if exists "Editors can manage pages" on public.cms_pages;
create policy "Editors can manage pages"
on public.cms_pages
for all
using (public.is_cms_editor())
with check (public.is_cms_editor());

drop policy if exists "Public can read active sections" on public.cms_sections;
create policy "Public can read active sections"
on public.cms_sections
for select
using (
  is_active = true
  and exists (
    select 1
    from public.cms_pages p
    where p.id = cms_sections.page_id
      and p.is_published = true
  )
  or public.is_cms_editor()
);

drop policy if exists "Editors can manage sections" on public.cms_sections;
create policy "Editors can manage sections"
on public.cms_sections
for all
using (public.is_cms_editor())
with check (public.is_cms_editor());

drop policy if exists "Public can read active section items" on public.cms_section_items;
create policy "Public can read active section items"
on public.cms_section_items
for select
using (
  is_active = true
  and exists (
    select 1
    from public.cms_sections s
    join public.cms_pages p on p.id = s.page_id
    where s.id = cms_section_items.section_id
      and s.is_active = true
      and p.is_published = true
  )
  or public.is_cms_editor()
);

drop policy if exists "Editors can manage section items" on public.cms_section_items;
create policy "Editors can manage section items"
on public.cms_section_items
for all
using (public.is_cms_editor())
with check (public.is_cms_editor());

drop policy if exists "Users can read own profile" on public.users;
create policy "Users can read own profile"
on public.users
for select
using (auth.uid() = id);

drop policy if exists "Editors can read all CMS users" on public.users;
create policy "Editors can read all CMS users"
on public.users
for select
using (public.is_cms_editor());

drop policy if exists "Editors can manage CMS users" on public.users;
create policy "Editors can manage CMS users"
on public.users
for all
using (public.is_cms_editor())
with check (public.is_cms_editor());

insert into public.cms_pages (
  slug,
  nav_label,
  page_title,
  page_description,
  seo_title,
  seo_description,
  hero_title,
  hero_body,
  hero_primary_button_label,
  hero_primary_button_url,
  hero_secondary_button_label,
  hero_secondary_button_url,
  sort_order
)
values
  (
    'home',
    'Home',
    'Secure Your Future with the Right Financial and Insurance Guidance',
    'We help individuals, families, and professionals understand their insurance options, protect their income, and build a better financial future.',
    'Home',
    'Financial and insurance guidance for individuals, families, and professionals.',
    'Secure Your Future with the Right Financial and Insurance Guidance',
    'We help individuals, families, and professionals understand their insurance options, protect their income, and build a better financial future.',
    'Book a Free Financial Review',
    '/contact',
    'Start Free Assessment',
    '/free-assessment',
    1
  ),
  (
    'about-us',
    'About Us',
    'About Us',
    'Learn about our mission, team, and approach to financial protection.',
    'About Us',
    'Learn about our mission, team, and approach to financial protection.',
    'Trusted guidance for every stage of life',
    'We help clients make confident decisions with practical financial and insurance advice.',
    'Talk to Our Team',
    '/contact',
    '',
    '',
    2
  ),
  (
    'services',
    'Services',
    'Services',
    'Explore our insurance and financial planning services.',
    'Services',
    'Explore our insurance and financial planning services.',
    'Services tailored to your goals',
    'From life insurance to retirement planning, we structure coverage around your priorities.',
    'Request a Consultation',
    '/contact',
    '',
    '',
    3
  ),
  (
    'free-assessment',
    'Free Assessment',
    'Free Assessment',
    'Start with a no-obligation review of your current protection and goals.',
    'Free Assessment',
    'Start with a no-obligation review of your current protection and goals.',
    'Get a free financial assessment',
    'Answer a few questions and our team will recommend next steps.',
    'Start Assessment',
    '/contact',
    '',
    '',
    4
  ),
  (
    'resources',
    'Resources',
    'Resources',
    'Helpful articles, guides, and planning tools.',
    'Resources',
    'Helpful articles, guides, and planning tools.',
    'Financial resources that make decisions easier',
    'Browse practical content built to help you understand options and take action.',
    'View Resources',
    '/resources',
    '',
    '',
    5
  ),
  (
    'join-our-team',
    'Join Our Team',
    'Join Our Team',
    'Build a meaningful career helping others secure their future.',
    'Join Our Team',
    'Build a meaningful career helping others secure their future.',
    'Join a growing financial team',
    'Receive training, mentorship, and career support while helping clients protect what matters.',
    'Apply Now',
    '/join-our-team',
    '',
    '',
    6
  ),
  (
    'contact',
    'Contact',
    'Contact',
    'Reach out to schedule a consultation or ask a question.',
    'Contact',
    'Reach out to schedule a consultation or ask a question.',
    'Talk to an advisor',
    'We are here to answer your questions and help you plan the right next step.',
    'Book a Consultation',
    '/contact',
    '',
    '',
    7
  )
on conflict (slug) do nothing;
