-- Financial Services CMS schema for Supabase
-- This model keeps layout/components in React and stores editable content in tables.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  site_name text not null,
  logo_url text default '',
  footer_cta_visible boolean not null default true,
  footer_cta_title text default '',
  footer_cta_body text default '',
  footer_cta_button_label text default '',
  footer_cta_button_url text default '',
  office_location_title text default 'Office Location',
  office_location_address text default '',
  contact_phone text default '',
  contact_email text default '',
  social_links jsonb not null default '[]'::jsonb,
  footer_quicklinks_visible boolean not null default true,
  copyright_name text default 'ZPG Eagle Financial Team',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint site_settings_single_row check (id = 1)
);

alter table public.site_settings add column if not exists footer_cta_visible boolean not null default true;
alter table public.site_settings add column if not exists office_location_title text default 'Office Location';
alter table public.site_settings add column if not exists office_location_address text default '';
alter table public.site_settings add column if not exists contact_phone text default '';
alter table public.site_settings add column if not exists contact_email text default '';
alter table public.site_settings add column if not exists social_links jsonb not null default '[]'::jsonb;
alter table public.site_settings add column if not exists footer_quicklinks_visible boolean not null default true;
alter table public.site_settings add column if not exists copyright_name text default 'ZPG Eagle Financial Team';

create table if not exists public.cms_pages (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  nav_label text not null,
  page_title text not null,
  page_description text default '',
  seo_title text default '',
  seo_description text default '',
  hero_title text default '',
  hero_body text default '',
  hero_primary_button_label text default '',
  hero_primary_button_url text default '',
  hero_secondary_button_label text default '',
  hero_secondary_button_url text default '',
  hero_image_url text default '',
  hero_visible boolean not null default true,
  is_published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.cms_pages add column if not exists hero_visible boolean not null default true;

create table if not exists public.cms_sections (
  id uuid primary key default gen_random_uuid(),
  page_id uuid not null references public.cms_pages(id) on delete cascade,
  section_key text not null,
  section_label text not null,
  section_type text not null check (
    section_type in (
      'hero',
      'content',
      'cards',
      'cta',
      'faq',
      'list'
    )
  ),
  title text default '',
  subtitle text default '',
  body text default '',
  image_url text default '',
  primary_button_label text default '',
  primary_button_url text default '',
  secondary_button_label text default '',
  secondary_button_url text default '',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint cms_sections_page_key_unique unique (page_id, section_key)
);

create table if not exists public.cms_section_items (
  id uuid primary key default gen_random_uuid(),
  section_id uuid not null references public.cms_sections(id) on delete cascade,
  title text not null,
  subtitle text default '',
  body text default '',
  image_url text default '',
  link_label text default '',
  link_url text default '',
  metadata jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  email text not null unique,
  role text not null default 'editor' check (role in ('admin', 'editor')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- Uploaded image/document files live in Supabase Storage. Content tables store
-- public URLs as text so pages can render them directly.
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'site-assets',
  'site-assets',
  true,
  10485760,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'image/svg+xml',
    'application/pdf'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  bucket_id text not null default 'site-assets',
  object_path text not null,
  public_url text not null default '',
  file_name text not null default '',
  mime_type text not null default '',
  file_size_bytes bigint,
  asset_type text not null default 'image' check (asset_type in ('image', 'document', 'other')),
  alt_text text default '',
  caption text default '',
  uploaded_by uuid references auth.users(id) on delete set null default auth.uid(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint media_assets_bucket_path_unique unique (bucket_id, object_path)
);

create table if not exists public.contact_leads (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  email text not null,
  phone text default '',
  preferred_contact_method text default '',
  subject text default '',
  message text default '',
  source_page text default 'contact',
  status text not null default 'new' check (status in ('new', 'contacted', 'qualified', 'closed', 'spam')),
  assigned_to uuid references public.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.assessment_submissions (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid references public.contact_leads(id) on delete set null,
  full_name text not null default '',
  email text not null default '',
  phone text default '',
  goals text[] not null default '{}'::text[],
  answers jsonb not null default '{}'::jsonb,
  result_summary text default '',
  recommendation text default '',
  status text not null default 'new' check (status in ('new', 'reviewed', 'follow_up', 'closed')),
  assigned_to uuid references public.users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.consultations (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid references public.contact_leads(id) on delete set null,
  assessment_submission_id uuid references public.assessment_submissions(id) on delete set null,
  scheduled_at timestamptz,
  timezone text default 'UTC',
  meeting_type text not null default 'phone' check (meeting_type in ('phone', 'video', 'in_person', 'other')),
  location_or_link text default '',
  status text not null default 'requested' check (status in ('requested', 'scheduled', 'completed', 'cancelled', 'no_show')),
  notes text default '',
  advisor_id uuid references public.users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.team_applications (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  email text not null,
  phone text default '',
  location text default '',
  experience_level text default '',
  resume_url text default '',
  portfolio_url text default '',
  message text default '',
  status text not null default 'new' check (status in ('new', 'reviewing', 'interview', 'accepted', 'declined')),
  reviewed_by uuid references public.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.advisor_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references public.users(id) on delete set null,
  display_name text not null,
  title text default '',
  bio text default '',
  headshot_url text default '',
  email text default '',
  phone text default '',
  license_text text default '',
  specialties text[] not null default '{}'::text[],
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- Seed the Join Our Team CMS page if it is missing. The admin editor uses the
-- generic cms_pages, cms_sections, and cms_section_items tables for CRUD.
insert into public.cms_pages (
  slug,
  nav_label,
  page_title,
  page_description,
  seo_title,
  seo_description,
  hero_title,
  hero_body,
  hero_primary_button_label,
  hero_primary_button_url,
  hero_image_url,
  hero_visible,
  is_published,
  sort_order
)
values (
  'join-our-team',
  'Join Our Team',
  'Join Our Team',
  'Build a meaningful career helping clients protect their future.',
  'Join Our Team',
  'Apply to join our financial services team and grow through training, mentorship, and client service.',
  'Join Our Team',
  'Work with experienced mentors, learn the financial services process, and grow with a team that supports your next step.',
  'Apply Now',
  '#join-application',
  '',
  true,
  true,
  5
)
on conflict (slug) do nothing;

with join_page as (
  select id
  from public.cms_pages
  where slug = 'join-our-team'
)
insert into public.cms_sections (
  page_id,
  section_key,
  section_label,
  section_type,
  title,
  body,
  sort_order,
  is_active
)
select id, 'mentorship-spotlight', 'Mentorship Spotlight', 'cards', 'Mentorship Spotlight', 'Show mentorship stories that encourage visitors to apply.', 1, true
from join_page
union all
select id, 'career-benefits', 'Why Join Us', 'cards', 'Why Join Our Team', 'Simple reasons people choose to build a career with us.', 2, true
from join_page
on conflict (page_id, section_key) do nothing;

with mentorship_section as (
  select s.id
  from public.cms_sections s
  join public.cms_pages p on p.id = s.page_id
  where p.slug = 'join-our-team'
    and s.section_key = 'mentorship-spotlight'
),
mentorship_items(title, subtitle, body, link_label, link_url, sort_order) as (
  values
    ('Training and Mentorship', 'Learn with support', 'Receive practical guidance, client-service training, and support from people who want to help you build confidence.', '', '', 1),
    ('Career Growth', 'Build your next step', 'Grow through hands-on experience, team support, and a clear path to serving clients well.', '', '', 2)
)
insert into public.cms_section_items (
  section_id,
  title,
  subtitle,
  body,
  image_url,
  link_label,
  link_url,
  sort_order,
  is_active
)
select
  mentorship_section.id,
  mentorship_items.title,
  mentorship_items.subtitle,
  mentorship_items.body,
  '',
  mentorship_items.link_label,
  mentorship_items.link_url,
  mentorship_items.sort_order,
  true
from mentorship_section
cross join mentorship_items
where not exists (
  select 1
  from public.cms_section_items existing
  where existing.section_id = mentorship_section.id
    and existing.title = mentorship_items.title
);

with benefits_section as (
  select s.id
  from public.cms_sections s
  join public.cms_pages p on p.id = s.page_id
  where p.slug = 'join-our-team'
    and s.section_key = 'career-benefits'
),
benefit_items(title, subtitle, body, link_label, link_url, sort_order) as (
  values
    ('Training', 'Start with guidance', 'Learn the financial services process through structured support and practical coaching.', '', '', 1),
    ('Mentorship', 'Work with experienced people', 'Get help from a team that understands client service, career growth, and daily execution.', '', '', 2),
    ('Growth', 'Build long-term skills', 'Develop communication, planning, and relationship skills while helping clients protect their future.', '', '', 3)
)
insert into public.cms_section_items (
  section_id,
  title,
  subtitle,
  body,
  image_url,
  link_label,
  link_url,
  sort_order,
  is_active
)
select
  benefits_section.id,
  benefit_items.title,
  benefit_items.subtitle,
  benefit_items.body,
  '',
  benefit_items.link_label,
  benefit_items.link_url,
  benefit_items.sort_order,
  true
from benefits_section
cross join benefit_items
where not exists (
  select 1
  from public.cms_section_items existing
  where existing.section_id = benefits_section.id
    and existing.title = benefit_items.title
);

create index if not exists idx_media_assets_bucket_path on public.media_assets(bucket_id, object_path);
create index if not exists idx_contact_leads_status_created_at on public.contact_leads(status, created_at desc);
create index if not exists idx_assessment_submissions_status_created_at on public.assessment_submissions(status, created_at desc);
create index if not exists idx_consultations_status_scheduled_at on public.consultations(status, scheduled_at);
create index if not exists idx_team_applications_status_created_at on public.team_applications(status, created_at desc);
create index if not exists idx_advisor_profiles_active_order on public.advisor_profiles(is_active, sort_order);

create or replace function public.is_cms_editor()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.users u
    where u.id = auth.uid()
      and u.role in ('admin', 'editor')
  );
$$;

drop trigger if exists trg_site_settings_updated_at on public.site_settings;
create trigger trg_site_settings_updated_at
before update on public.site_settings
for each row
execute function public.set_updated_at();

drop trigger if exists trg_cms_pages_updated_at on public.cms_pages;
create trigger trg_cms_pages_updated_at
before update on public.cms_pages
for each row
execute function public.set_updated_at();

drop trigger if exists trg_cms_sections_updated_at on public.cms_sections;
create trigger trg_cms_sections_updated_at
before update on public.cms_sections
for each row
execute function public.set_updated_at();

drop trigger if exists trg_cms_section_items_updated_at on public.cms_section_items;
create trigger trg_cms_section_items_updated_at
before update on public.cms_section_items
for each row
execute function public.set_updated_at();

drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
before update on public.users
for each row
execute function public.set_updated_at();

drop trigger if exists trg_media_assets_updated_at on public.media_assets;
create trigger trg_media_assets_updated_at
before update on public.media_assets
for each row
execute function public.set_updated_at();

drop trigger if exists trg_contact_leads_updated_at on public.contact_leads;
create trigger trg_contact_leads_updated_at
before update on public.contact_leads
for each row
execute function public.set_updated_at();

drop trigger if exists trg_assessment_submissions_updated_at on public.assessment_submissions;
create trigger trg_assessment_submissions_updated_at
before update on public.assessment_submissions
for each row
execute function public.set_updated_at();

drop trigger if exists trg_consultations_updated_at on public.consultations;
create trigger trg_consultations_updated_at
before update on public.consultations
for each row
execute function public.set_updated_at();

drop trigger if exists trg_team_applications_updated_at on public.team_applications;
create trigger trg_team_applications_updated_at
before update on public.team_applications
for each row
execute function public.set_updated_at();

drop trigger if exists trg_advisor_profiles_updated_at on public.advisor_profiles;
create trigger trg_advisor_profiles_updated_at
before update on public.advisor_profiles
for each row
execute function public.set_updated_at();

alter table public.site_settings enable row level security;
alter table public.cms_pages enable row level security;
alter table public.cms_sections enable row level security;
alter table public.cms_section_items enable row level security;
alter table public.users enable row level security;
alter table public.media_assets enable row level security;
alter table public.contact_leads enable row level security;
alter table public.assessment_submissions enable row level security;
alter table public.consultations enable row level security;
alter table public.team_applications enable row level security;
alter table public.advisor_profiles enable row level security;

drop policy if exists "Public can read site assets" on storage.objects;
create policy "Public can read site assets"
on storage.objects
for select
using (bucket_id = 'site-assets');

drop policy if exists "Editors can upload site assets" on storage.objects;
create policy "Editors can upload site assets"
on storage.objects
for insert
with check (bucket_id = 'site-assets' and public.is_cms_editor());

drop policy if exists "Editors can update site assets" on storage.objects;
create policy "Editors can update site assets"
on storage.objects
for update
using (bucket_id = 'site-assets' and public.is_cms_editor())
with check (bucket_id = 'site-assets' and public.is_cms_editor());

drop policy if exists "Editors can delete site assets" on storage.objects;
create policy "Editors can delete site assets"
on storage.objects
for delete
using (bucket_id = 'site-assets' and public.is_cms_editor());

drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings"
on public.site_settings
for select
using (true);

drop policy if exists "Editors can manage site settings" on public.site_settings;
create policy "Editors can manage site settings"
on public.site_settings
for all
using (public.is_cms_editor())
with check (public.is_cms_editor());

drop policy if exists "Public can read published pages" on public.cms_pages;
create policy "Public can read published pages"
on public.cms_pages
for select
using (is_published = true or public.is_cms_editor());

drop policy if exists "Editors can manage pages" on public.cms_pages;
create policy "Editors can manage pages"
on public.cms_pages
for all
using (public.is_cms_editor())
with check (public.is_cms_editor());

drop policy if exists "Public can read active sections" on public.cms_sections;
create policy "Public can read active sections"
on public.cms_sections
for select
using (
  is_active = true
  and exists (
    select 1
    from public.cms_pages p
    where p.id = cms_sections.page_id
      and p.is_published = true
  )
  or public.is_cms_editor()
);

drop policy if exists "Editors can manage sections" on public.cms_sections;
create policy "Editors can manage sections"
on public.cms_sections
for all
using (public.is_cms_editor())
with check (public.is_cms_editor());

drop policy if exists "Public can read active section items" on public.cms_section_items;
create policy "Public can read active section items"
on public.cms_section_items
for select
using (
  is_active = true
  and exists (
    select 1
    from public.cms_sections s
    join public.cms_pages p on p.id = s.page_id
    where s.id = cms_section_items.section_id
      and s.is_active = true
      and p.is_published = true
  )
  or public.is_cms_editor()
);

drop policy if exists "Editors can manage section items" on public.cms_section_items;
create policy "Editors can manage section items"
on public.cms_section_items
for all
using (public.is_cms_editor())
with check (public.is_cms_editor());

drop policy if exists "Users can read own profile" on public.users;
create policy "Users can read own profile"
on public.users
for select
using (auth.uid() = id);

drop policy if exists "Public can resolve login usernames" on public.users;
create policy "Public can resolve login usernames"
on public.users
for select
using (true);

drop policy if exists "Editors can read all CMS users" on public.users;
create policy "Editors can read all CMS users"
on public.users
for select
using (public.is_cms_editor());

drop policy if exists "Editors can manage CMS users" on public.users;
create policy "Editors can manage CMS users"
on public.users
for all
using (public.is_cms_editor())
with check (public.is_cms_editor());

drop policy if exists "Public can read media assets" on public.media_assets;
create policy "Public can read media assets"
on public.media_assets
for select
using (true);

drop policy if exists "Editors can manage media assets" on public.media_assets;
create policy "Editors can manage media assets"
on public.media_assets
for all
using (public.is_cms_editor())
with check (public.is_cms_editor());

drop policy if exists "Public can create contact leads" on public.contact_leads;
create policy "Public can create contact leads"
on public.contact_leads
for insert
to anon, authenticated
with check (true);

drop policy if exists "Editors can manage contact leads" on public.contact_leads;
create policy "Editors can manage contact leads"
on public.contact_leads
for all
using (public.is_cms_editor())
with check (public.is_cms_editor());

drop policy if exists "Public can create assessment submissions" on public.assessment_submissions;
create policy "Public can create assessment submissions"
on public.assessment_submissions
for insert
to anon, authenticated
with check (true);

drop policy if exists "Editors can manage assessment submissions" on public.assessment_submissions;
create policy "Editors can manage assessment submissions"
on public.assessment_submissions
for all
using (public.is_cms_editor())
with check (public.is_cms_editor());

drop policy if exists "Public can request consultations" on public.consultations;
create policy "Public can request consultations"
on public.consultations
for insert
to anon, authenticated
with check (status = 'requested' and advisor_id is null);

drop policy if exists "Editors can manage consultations" on public.consultations;
create policy "Editors can manage consultations"
on public.consultations
for all
using (public.is_cms_editor())
with check (public.is_cms_editor());

drop policy if exists "Public can create team applications" on public.team_applications;
create policy "Public can create team applications"
on public.team_applications
for insert
to anon, authenticated
with check (true);

drop policy if exists "Editors can manage team applications" on public.team_applications;
create policy "Editors can manage team applications"
on public.team_applications
for all
using (public.is_cms_editor())
with check (public.is_cms_editor());

drop policy if exists "Public can read active advisor profiles" on public.advisor_profiles;
create policy "Public can read active advisor profiles"
on public.advisor_profiles
for select
using (is_active = true or public.is_cms_editor());

drop policy if exists "Editors can manage advisor profiles" on public.advisor_profiles;
create policy "Editors can manage advisor profiles"
on public.advisor_profiles
for all
using (public.is_cms_editor())
with check (public.is_cms_editor());
